name: math_keyboard
description: >-2
  Math expression editing using an on-screen software keyboard or physical keyboard input in a
  typeset input field in Flutter.
version: 0.3.2
homepage: https://github.com/simpleclub/math_keyboard/tree/main/math_keyboard

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_math_fork: ^0.7.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.3.1
  holding_gesture: ^1.2.0
  intl: ^0.19.0
  math_expressions: ^2.5.0
  petitparser: ^6.0.0

dependency_overrides: 
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  assets:
    - assets/images/VirtualKeyboard/
  fonts:
  - family: CustomKeyIcons
    fonts:
    - asset: fonts/CustomKeyIcons.ttf

